"""Summary text export functionality for ProcessIQ analysis results."""

import logging
from datetime import UTC, datetime

from processiq.models import BusinessProfile, Constraints, ProcessData
from processiq.models.insight import AnalysisInsight

logger = logging.getLogger(__name__)


def export_insight_text(insight: AnalysisInsight) -> str:
    """Export AnalysisInsight as formatted text summary.

    Args:
        insight: LLM-generated analysis insight.

    Returns:
        Formatted text summary.
    """
    lines = []

    # Header
    lines.append("=" * 60)
    lines.append("PROCESSIQ ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Summary
    lines.append("-" * 60)
    lines.append("SUMMARY")
    lines.append("-" * 60)
    lines.append(insight.process_summary)
    lines.append("")

    # Issues
    lines.append("-" * 60)
    lines.append(f"ISSUES IDENTIFIED ({len(insight.issues)})")
    lines.append("-" * 60)
    if insight.issues:
        for i, issue in enumerate(insight.issues, 1):
            lines.append(f"{i}. {issue.title}")
            lines.append(f"   Severity: {issue.severity.upper()}")
            lines.append(f"   {issue.description}")
            if issue.affected_steps:
                lines.append(f"   Affects: {', '.join(issue.affected_steps)}")
            if issue.root_cause_hypothesis:
                lines.append(f"   Root cause: {issue.root_cause_hypothesis}")
            lines.append("")
    else:
        lines.append("No significant issues identified.")
        lines.append("")

    # Recommendations
    lines.append("-" * 60)
    lines.append(f"RECOMMENDATIONS ({len(insight.recommendations)})")
    lines.append("-" * 60)
    if insight.recommendations:
        for i, rec in enumerate(insight.recommendations, 1):
            lines.append(f"{i}. {rec.title}")
            lines.append(f"   Addresses: {rec.addresses_issue}")
            lines.append(f"   Feasibility: {rec.feasibility}")
            lines.append(f"   {rec.description}")
            if rec.expected_benefit:
                lines.append(f"   Expected benefit: {rec.expected_benefit}")
            if rec.risks:
                lines.append("   Risks:")
                for risk in rec.risks:
                    lines.append(f"      - {risk}")
            if rec.concrete_next_steps:
                lines.append("   Next steps:")
                for step in rec.concrete_next_steps:
                    lines.append(f"      - {step}")
            lines.append("")
    else:
        lines.append("No recommendations generated.")
        lines.append("")

    # Core value work
    if insight.not_problems:
        lines.append("-" * 60)
        lines.append(f"CORE VALUE WORK ({len(insight.not_problems)})")
        lines.append("-" * 60)
        for np in insight.not_problems:
            lines.append(f"- {np.step_name}: {np.why_not_a_problem}")
        lines.append("")

    # Patterns
    if insight.patterns:
        lines.append("-" * 60)
        lines.append("PATTERNS DETECTED")
        lines.append("-" * 60)
        for pattern in insight.patterns:
            lines.append(f"- {pattern}")
        lines.append("")

    # Caveats
    if insight.confidence_notes:
        lines.append("-" * 60)
        lines.append("CAVEATS")
        lines.append("-" * 60)
        lines.append(insight.confidence_notes)
        lines.append("")

    # Footer
    lines.append("=" * 60)
    lines.append("Generated by ProcessIQ - AI-Powered Process Optimization")
    lines.append("=" * 60)

    logger.info("Generated text summary from insight")
    return "\n".join(lines)


def export_insight_markdown(insight: AnalysisInsight) -> str:
    """Export AnalysisInsight as markdown summary.

    Args:
        insight: LLM-generated analysis insight.

    Returns:
        Markdown formatted summary.
    """
    lines = []

    # Header
    lines.append("# ProcessIQ Analysis Report")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(insight.process_summary)
    lines.append("")

    # Issues
    lines.append(f"## Issues Identified ({len(insight.issues)})")
    lines.append("")
    if insight.issues:
        lines.append("| # | Issue | Severity | Affected Steps |")
        lines.append("|---|-------|----------|----------------|")
        for i, issue in enumerate(insight.issues, 1):
            steps = ", ".join(issue.affected_steps) if issue.affected_steps else "-"
            lines.append(
                f"| {i} | {issue.title} | {issue.severity.upper()} | {steps} |"
            )
        lines.append("")
        for i, issue in enumerate(insight.issues, 1):
            lines.append(f"### {i}. {issue.title}")
            lines.append("")
            lines.append(issue.description)
            if issue.root_cause_hypothesis:
                lines.append("")
                lines.append(
                    f"**Root cause hypothesis:** {issue.root_cause_hypothesis}"
                )
            if issue.evidence:
                lines.append("")
                lines.append("**Evidence:**")
                for ev in issue.evidence:
                    lines.append(f"- {ev}")
            lines.append("")
    else:
        lines.append("*No significant issues identified.*")
        lines.append("")

    # Recommendations
    lines.append(f"## Recommendations ({len(insight.recommendations)})")
    lines.append("")
    if insight.recommendations:
        for i, rec in enumerate(insight.recommendations, 1):
            lines.append(f"### {i}. {rec.title}")
            lines.append("")
            lines.append(f"- **Addresses:** {rec.addresses_issue}")
            lines.append(f"- **Feasibility:** {rec.feasibility}")
            if rec.expected_benefit:
                lines.append(f"- **Expected benefit:** {rec.expected_benefit}")
            lines.append("")
            lines.append(rec.description)
            if rec.risks:
                lines.append("")
                lines.append("**Risks:**")
                for risk in rec.risks:
                    lines.append(f"- {risk}")
            if rec.concrete_next_steps:
                lines.append("")
                lines.append("**Next steps:**")
                for j, next_step in enumerate(rec.concrete_next_steps, 1):
                    lines.append(f"{j}. {next_step}")
            lines.append("")
    else:
        lines.append("*No recommendations generated.*")
        lines.append("")

    # Core value work
    if insight.not_problems:
        lines.append("## Core Value Work")
        lines.append("")
        lines.append(
            "*These steps may look like bottlenecks but are where real value is created:*"
        )
        lines.append("")
        for np in insight.not_problems:
            lines.append(f"- **{np.step_name}:** {np.why_not_a_problem}")
        lines.append("")

    # Patterns
    if insight.patterns:
        lines.append("## Patterns Detected")
        lines.append("")
        for pattern in insight.patterns:
            lines.append(f"- {pattern}")
        lines.append("")

    # Caveats
    if insight.confidence_notes:
        lines.append("## Caveats")
        lines.append("")
        lines.append(insight.confidence_notes)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by ProcessIQ - AI-Powered Process Optimization*")

    logger.info("Generated markdown summary from insight")
    return "\n".join(lines)


def generate_proposal_markdown(
    insight: AnalysisInsight,
    process_data: ProcessData,
    profile: BusinessProfile | None = None,
    constraints: Constraints | None = None,
) -> str:
    """Export AnalysisInsight as a business-audience markdown proposal.

    Suitable for pasting into Notion, Confluence, or Google Docs.
    Format: Executive Summary → Current State → Key Findings → Recommendations → Next Steps → Appendix.

    Args:
        insight: LLM-generated analysis insight.
        process_data: The analyzed process.
        profile: Optional business profile (industry, company size).
        constraints: Optional constraints that shaped recommendations.

    Returns:
        Markdown formatted business proposal.
    """
    lines = []

    # Title
    lines.append(f"# Process Improvement Proposal: {process_data.name}")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(insight.process_summary)
    lines.append("")
    total_time = sum(s.average_time_hours for s in process_data.steps)
    total_cost = sum(s.cost_per_instance for s in process_data.steps)
    lines.append(
        f"**Process snapshot:** {len(process_data.steps)} steps, "
        f"{total_time:.1f} hours per run"
    )
    if total_cost > 0:
        lines.append(f", ${total_cost:,.0f} cost per run")
    lines.append("")

    # Current State (description of the process)
    lines.append("## Current Process")
    lines.append("")
    if process_data.description:
        lines.append(process_data.description)
        lines.append("")
    lines.append("**Steps:**")
    lines.append("")
    for i, step in enumerate(process_data.steps, 1):
        lines.append(f"{i}. **{step.step_name}** — {step.average_time_hours:.1f} hours")
        if step.cost_per_instance > 0:
            lines.append(f"   - Cost: ${step.cost_per_instance:,.0f}")
        if step.depends_on:
            lines.append(f"   - Depends on: {', '.join(step.depends_on)}")
    lines.append("")

    # Key Findings (issues identified)
    if insight.issues:
        lines.append("## Key Findings")
        lines.append("")
        for i, issue in enumerate(insight.issues, 1):
            lines.append(f"### {i}. {issue.title}")
            lines.append("")
            lines.append(f"**Severity:** {issue.severity.upper()}")
            lines.append("")
            lines.append(issue.description)
            if issue.affected_steps:
                lines.append("")
                lines.append(f"**Affected steps:** {', '.join(issue.affected_steps)}")
            if issue.root_cause_hypothesis:
                lines.append("")
                lines.append(f"**Root cause:** {issue.root_cause_hypothesis}")
            lines.append("")
    else:
        lines.append("## Key Findings")
        lines.append("")
        lines.append(
            "No significant issues identified. The process is running smoothly."
        )
        lines.append("")

    # Recommendations (with action orientation)
    if insight.recommendations:
        lines.append("## Recommendations for Improvement")
        lines.append("")
        lines.append(
            "Each recommendation below includes the change, expected impact, "
            "feasibility, and next steps."
        )
        lines.append("")
        for i, rec in enumerate(insight.recommendations, 1):
            lines.append(f"### {i}. {rec.title}")
            lines.append("")
            lines.append(rec.description)
            lines.append("")
            if rec.expected_benefit:
                lines.append(f"**Expected benefit:** {rec.expected_benefit}")
                lines.append("")
            lines.append(f"**Feasibility:** {rec.feasibility}")
            if rec.estimated_roi:
                lines.append(f"  |  **Estimated ROI:** {rec.estimated_roi}")
            lines.append("")
            if rec.risks:
                lines.append("**Risks & Trade-offs:**")
                for risk in rec.risks:
                    lines.append(f"- {risk}")
                lines.append("")
            if rec.concrete_next_steps:
                lines.append("**How to get started:**")
                for j, next_step in enumerate(rec.concrete_next_steps, 1):
                    lines.append(f"{j}. {next_step}")
                lines.append("")
    else:
        lines.append("## Recommendations")
        lines.append("")
        lines.append("No recommendations generated at this time.")
        lines.append("")

    # Suggested Next Steps
    lines.append("## Suggested Next Steps")
    lines.append("")
    lines.append(
        "1. **Review & Validate** — Share these findings with your team to confirm accuracy"
    )
    lines.append(
        "2. **Prioritize** - Choose 1-2 recommendations to pilot (start with high-impact, low-complexity)"
    )
    lines.append(
        "3. **Plan** — Define timeline, resources, and success metrics for each pilot"
    )
    lines.append("4. **Execute** — Run the pilot and track results")
    lines.append(
        "5. **Measure & Iterate** — Compare before/after metrics and refine as needed"
    )
    lines.append("")

    # Appendix (data & assumptions)
    lines.append("## Appendix: Data & Assumptions")
    lines.append("")
    if profile:
        lines.append(
            f"**Industry:** {profile.industry.value if profile.industry else 'Not specified'}"
        )
        if profile.company_size:
            lines.append(f"**Company Size:** {profile.company_size.value}")
        lines.append("")
    if constraints:
        constraints_list = []
        if constraints.budget_limit:
            constraints_list.append(f"Budget limit: {constraints.budget_limit}")
        if constraints.max_implementation_weeks:
            constraints_list.append(
                f"Timeline: {constraints.max_implementation_weeks} weeks"
            )
        if constraints.custom_constraints:
            constraints_list.append(
                f"Other: {', '.join(constraints.custom_constraints)}"
            )
        if constraints_list:
            lines.append("**Constraints:**")
            for c in constraints_list:
                lines.append(f"- {c}")
            lines.append("")
    lines.append(
        f"**Generated:** {datetime.now(UTC).strftime('%B %d, %Y at %H:%M UTC')}"
    )
    lines.append("")
    lines.append("---")
    lines.append("*ProcessIQ — AI-Powered Process Optimization*")

    logger.info("Generated business proposal markdown from insight")
    return "\n".join(lines)
